# Generated by Django 2.0.5 on 2018-12-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('mobile', models.BigIntegerField()),
                ('black_listed', models.BooleanField(default=False)),
            ],
        ),
    ]
