# Generated by Django 2.0.5 on 2018-12-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_auto_20181219_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
