# Generated by Django 2.0.5 on 2018-12-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=100)),
                ('singleRoomsCount', models.IntegerField(default=0)),
                ('doubleRoomsCount', models.IntegerField(default=0)),
                ('singelRoomsPrice', models.IntegerField(default=0)),
                ('doubleRoomsPrice', models.IntegerField(default=0)),
                ('stars', models.IntegerField()),
                ('image', models.ImageField(upload_to='media')),
                ('state', models.CharField(default='Pending', max_length=100)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.owner')),
            ],
        ),
    ]
