# Generated by Django 2.0.5 on 2018-12-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='imageD',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='requests',
            name='imageS',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
