# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='hotel_location_id',
        ),
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
