# Generated by Django 2.1.4 on 2018-12-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='hotel_location_id',
        ),
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(default='Alexandria', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='country',
            field=models.CharField(default='Egypt', max_length=100),
            preserve_default=False,
        ),
    ]
