# Generated by Django 2.0.5 on 2018-12-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_auto_20181219_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='singelRoomsPrice',
            new_name='singleRoomsPrice',
        ),
    ]
