# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-18 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_auto_20181218_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requests',
        ),
    ]
