# Generated by Django 2.1.4 on 2018-12-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_auto_20181219_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
