# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-18 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0003_auto_20181218_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='owner_id',
        ),
    ]
