# Generated by Django 2.1.4 on 2018-12-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0004_auto_20181219_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
