# Generated by Django 2.1.4 on 2018-12-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('country', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='media')),
                ('rates_count', models.IntegerField(default=0)),
                ('rates_sum', models.IntegerField(default=0)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.owner')),
            ],
        ),
    ]
