# Generated by Django 2.1.4 on 2018-12-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=None)),
                ('rates_count', models.IntegerField(default=0)),
                ('rates_sum', models.IntegerField(default=0)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
            ],
        ),
    ]
