# Generated by Django 2.0.5 on 2018-12-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='media')),
                ('rates_count', models.IntegerField(default=0)),
                ('rates_sum', models.IntegerField(default=0)),
            ],
        ),
    ]
