# Generated by Django 2.1.4 on 2018-12-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location_id',
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
