# Generated by Django 2.0.5 on 2018-12-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_suspended',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
