# Generated by Django 2.1.3 on 2018-12-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='owner_id',
        ),
    ]
