# Generated by Django 2.1.4 on 2018-12-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
        ('Hotel', '0002_auto_20181219_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Owner.owner'),
            preserve_default=False,
        ),
    ]
