# Generated by Django 2.1.4 on 2018-12-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_auto_20181214_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location_id',
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
