# Generated by Django 2.0.5 on 2018-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_hotel_is_suspended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='is_suspended',
            field=models.IntegerField(default=0),
        ),
    ]
