# Generated by Django 2.1.4 on 2018-12-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_auto_20181214_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_suspended',
            field=models.IntegerField(default=0),
        ),
    ]
