# Generated by Django 2.1.4 on 2018-12-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_auto_20181214_1825'),
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='hotel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotel'),
        ),
    ]
