# Generated by Django 2.1.3 on 2018-12-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='from_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='to_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
