# Generated by Django 2.1.4 on 2018-12-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_reservations_hotel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='hotel_id',
        ),
    ]
